/**
 * Safety panel with three sections:
 *   1. Current medicine list (and a "add sample Ibuprofen" shortcut for the demo).
 *   2. Interaction matrix rendered as a table with severity chips.
 *   3. Risk score gauge + talking points generated by `buildDiscussionPoints`.
 */

'use client';

import * as React from 'react';

import { Badge } from '@frontend/components/ui/badge';
import { Button } from '@frontend/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@frontend/components/ui/card';
import { Progress } from '@frontend/components/ui/progress';
import { useToast } from '@frontend/components/ui/toast';
import { usePatientStore } from '@frontend/state/patient_store';

import { regimenRiskScore } from '@backend/services/interaction_engine';
import { buildDiscussionPoints } from '@ml/risk_classifier';
import { findMedicine } from '@data/indian_medicines';
import { defaultSlotsFor } from '@data/pictograms';

export function SafetyPanel() {
  const medicines = usePatientStore((s) => s.medicines);
  const addMedicine = usePatientStore((s) => s.addMedicine);
  const { toast } = useToast();
  const risk = regimenRiskScore(medicines.map((m) => m.ingredient));
  const discussion = buildDiscussionPoints(risk.alerts, medicines.length);

  function addSample(brand: string) {
    const med = findMedicine(brand);
    if (!med) return;
    if (medicines.some((m) => m.ingredient.toLowerCase() === med.ingredient.toLowerCase())) {
      toast({ title: 'Already in your list', tone: 'info' });
      return;
    }
    addMedicine({
      id: `safety-sample-${Date.now()}`,
      brand: med.brand,
      ingredient: med.ingredient,
      strength: med.strength,
      rxcui: med.rxcui,
      slots: defaultSlotsFor(med.defaultFrequency),
      meal: 'after-meal',
    });
    toast({ title: `Added ${med.brand}`, description: 'Re-running the safety check.', tone: 'success' });
  }

  return (
    <div className="grid gap-6 lg:grid-cols-3">
      <Card className="lg:col-span-2">
        <CardHeader>
          <CardTitle>Interaction matrix</CardTitle>
          <p className="text-sm text-ink-muted">
            Every pairwise interaction across your current medicines, color-coded by severity.
          </p>
        </CardHeader>
        <CardContent>
          {risk.alerts.length === 0 ? (
            <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-900">
              ✅ No interactions detected across your {medicines.length} medicines.
            </div>
          ) : (
            <div className="overflow-hidden rounded-2xl border border-slate-200">
              <table className="w-full text-left text-sm">
                <thead className="bg-slate-50 text-xs uppercase tracking-wider text-ink-muted">
                  <tr>
                    <th className="px-4 py-2">Severity</th>
                    <th className="px-4 py-2">Pair</th>
                    <th className="px-4 py-2">Why it matters</th>
                    <th className="px-4 py-2">Source</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {risk.alerts.map((a, i) => (
                    <tr key={i} className="align-top">
                      <td className="px-4 py-3">
                        <Badge tone={a.severity}>{a.severity.toUpperCase()}</Badge>
                      </td>
                      <td className="px-4 py-3 font-medium text-ink">{capitalise(a.a)} ↔ {capitalise(a.b)}</td>
                      <td className="px-4 py-3 text-ink-muted">
                        {a.reason}
                        <div className="mt-1 text-xs"><strong>Advice:</strong> {a.advice}</div>
                      </td>
                      <td className="px-4 py-3 text-xs text-ink-muted">{a.source}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          <div className="mt-5 flex flex-wrap gap-2">
            <Button variant="outline" onClick={() => addSample('Combiflam')}>+ Try adding Combiflam</Button>
            <Button variant="outline" onClick={() => addSample('Ecosprin 75')}>+ Try adding Ecosprin</Button>
            <Button variant="outline" onClick={() => addSample('Azithral 500')}>+ Try adding Azithral</Button>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Polypharmacy risk score</CardTitle>
          <p className="text-sm text-ink-muted">
            Composite 0–100 index combining interaction severity and regimen size.
          </p>
        </CardHeader>
        <CardContent>
          <div className="mb-2 flex items-baseline gap-2">
            <span className="font-display text-5xl font-semibold text-ink">{risk.score}</span>
            <span className="text-sm text-ink-muted">/ 100</span>
          </div>
          <Progress value={risk.score} tone="severity" />
          <p className="mt-3 text-sm text-ink-muted">{risk.summary}</p>
          <div className="mt-5">
            <div className="mb-2 text-sm font-semibold text-ink">Three things to discuss with your doctor</div>
            <ol className="list-decimal space-y-2 pl-5 text-sm text-ink">
              {discussion.map((d, i) => (
                <li key={i} className="pl-1">{d}</li>
              ))}
            </ol>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function capitalise(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
